AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Sample SAM Template for sam-s3input-sample

Globals:
    Function:
        Timeout: 3

Resources:
    S3InputBucket:
        Type: AWS::S3::Bucket
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: hello_world/
            Handler: app.lambda_handler
            Runtime: python3.10
            Architectures:
                - x86_64
            Events:
                S3UploadEvent:
                    Type: S3
                    Properties:
                        Bucket: !Ref S3InputBucket
                        Events: s3:ObjectCreated:*
